### ISSUE TITLE
Remove DNS entry using CallSC

### ISSUE THREAD

**Issue by unholy0X** [massalabs/massa-standards#104]
Context
In the context of the ICO quests, we don't want to have the Massa Station page Massa Ecosystem polluted by test websites that the CI adds. So we should have the flexibility to delete and entry from the DNS using a CallSC

User flow
Describe the user flow using user stories so the end result is super clear - PM

How to
List the step-by-step to get it do if needed - PM

Technical details
Add function called `deleteEntry` to delete an entry completely from the DNS.  
Add unit tests to cover `deleteEntry`.

QA testing
Does this task require some QA tests ?
If yes, explain how to validate it

**Comment by longgamma-massa** [comment]
@B-Naoufal any q/a needed?
