### ISSUE TITLE
Incoherent checks in NFT standards

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/massa-standards#117]
The checks : https://github.com/massalabs/massa-standards/blob/523b3447f9b4a6cf8a30a1f6b0bc1c4451b8ef54/smart-contracts/assembly/contracts/NFT/NFT.ts#L340-L348 are not coherent with what the function does.

Some checks should be done to ensure security but this is clearly not the case of this one which are not related to this function and block some usecase

EDIT: The second check returns me "data entry not found" had to override the function with a version without the check to make it works

**Comment by Ben-Rey** [comment]
done here: https://github.com/massalabs/massa-standards/pull/118/files
