### ISSUE TITLE
WEB3-Wallet interaction standard

### ISSUE THREAD

**Issue by damip** [massalabs/massa-standards#13]
## Context

Currently, Thyra is not integrated with massa-web3, and each community wallet implements its own interface for communicating with web3 pages. We need to define a standard interface that every browser plugin will expose, and have massa-web3 also map thyra to that standard. That standard would define:
* a way for webpages using massa-web3 to auto-detect all installed wallets that follow the standard (browser plugins and/or Thyra)
* a way to manage the wallet if authorized by the user (add/remove keys)
* a way to list available accounts
* a way to ask a wallet to sign some data and return the signature

## User flow

```gherkin
  Given I am a developer creating a web3 site that uses massa-web3
  When My app needs to detect and all available wallets and interact with them seamlessly
  Then Massa-web3 should provide such a facility
```

```gherkin
  Given I am a user of a web3 app
  When I open the app
  Then The app needs to detect all the wallets I have installed (browser plugins, Thyra) and allow me to use any, or multiple of them seamlessly ans safely
```

```gherkin
  Given I am a community developer
  When I create a new Thyra-like project (heavy client), or wallet browser plugin
  Then I should easily find an interface standard and example implementation in the Massa documentation that explains which interface I need to expose in order to be auto-detected and managed seamlessly by massa-web3 
```

```gherkin
  Given I am a Massa developer working on massa-web3
  When I want massa-web3 to support all wallets
  Then I shouldn't be worried about past or future compatibility because the interface between web3 and all present and future wallets is standardized 
```

## How to

* define an interface standard in Massa standards
  * make sure the standard covers the cases of heavy clients (like Thyra) and the case of browser plugins
  * make sure the standard allows custom extensions specific to some wallets 
  * include a versioning system ensuring future-proofing
* implement the support of the standard in massa-web3
* provide documentation and examples
* synchronize with the community to update existing wallets up to standard

## Technical details

* browser plugins should inject themselves in the top window object, under their own ID (not overwrite other wallets)
* Thyra presence should be checked by massa-web3 through attempted connection, and if present, it should be exposed in Window as well under the same interface as the other wallets
* Followup: extra heavy clients (like thyra) can also be added transparently by requesting massa-web3 to ping a given ip/port (TODO discuss)

## QA testing

* proof-read the standard and documentation to ensure:
  * clarity
  * future-proofing
  * simplicity
  * flexibility
* test the examples
* try installing Thyra and community plugins, make sure that web3 pages detect them and interact with all of them seamlessly

**Comment by damip** [comment]
@massalabs/run @gregLibert FYI, to discuss

**Comment by damip** [comment]
@massalabs/innovation FYI, to discuss

**Comment by SlnPons** [comment]
Good point @damip! Happy it pops-up :) 
Thyra product strategy is to cover all these use cases described. Actually, they all are currently covered with Thyra plugin manager that allows all app to communicate and so wallets to be detected, signed, etc...

If I don't get it wrong, your point highlights the need to agree a more global strategy about massa-web3 and thyra as tools to communicate with Massa blockchain so we don't double the efforts. 
Did I get your point correctly or did I miss sth?

**Comment by damip** [comment]
> Good point @damip! Happy it pops-up :) Thyra product strategy is to cover all these use cases described. Actually, they all are currently covered with Thyra plugin manager that allows all app to communicate and so wallets to be detected, signed, etc...

> If I don't get it wrong, your point highlights the need to agree a more global strategy about massa-web3 and thyra as tools to communicate with Massa blockchain so we don't double the efforts. Did I get your point correctly or did I miss sth?

Thyra wallet is not integrated with massa-web3 and we need to integrate it somehow to provide a consistent toolset to web3 app developers. On the other hand, we have community wallets (browser plugins) like bearby or energy8 that use thier own interface. What this discussion is recommending is to have a standard interface allowing the massa-web3 to detect thyra and any other software or browser plugin following that standard, and transparently interact with them.

**Comment by SlnPons** [comment]
@damip I think there is a misunderstanding between what is Thyra and what is a wallet plug-in. 
Thyra is an app that provide easy-to-use tools for web3 dev and easy-to-use app for end-users so that they can interact with Massa blockchain. 
On top of Thyra, you can install a wallet plug-in. Massa's one (what I think you call Thyra wallet) or any other wallet built by the community. All plugins have their own interfaces.

**Comment by damip** [comment]
To clarify:
* what I called 'thyra wallet" is indeed the massa wallet plugin for thyra
* what I called "browser plugin" is something like bearby or energy8 or the old massa in-browser wallet
* what I call massa-web3 is the frontend javascript library that is used by web3 pages to communicate with whatever is available for interaction with the Massa network 

If you look at how Ethereum's web3 frontend library is designed: https://web3js.readthedocs.io you'll see that it follows a standard allowing anyone to develop a new wallet, and web3 apps can interact with any of those wallets ouf-of-the-box because they all follow the same standard interface.
In our case, currently, each wallet (Thyra's massa wallet plugin, the old massa plugin, energy8, bearby...) all follow their own thing because there is no standard, which makes it extremely hard to make a web3 app that works out-of-the-box with all wallets

**Comment by Thykof** [comment]
I think we also need a standard for defining who to write a wallet file: `wallet.dat`. So that the Thyra wallet plugin, the massa node and other wallet can generate the .dat file the same way. This standard will describe how the private key is encrypted and how to decrypt it.

@damip did you had in mind this when writing this issue? should we create another issue for the wallet file?

**Comment by damip** [comment]
> I think we also need a standard for defining who to write a wallet file: `wallet.dat`. So that the Thyra wallet plugin, the massa node and other wallet can generate the .dat file the same way. This standard will describe how the private key is encrypted and how to decrypt it.
> 
> @damip did you had in mind this when writing this issue? should we create another issue for the wallet file?

That's indeed another question that deserves its separate issue.

**Comment by damip** [comment]
> > browser plugins should inject themselves in the top window object, under their own ID (not overwrite other wallets)
> 
> I would do it in a different way:
> 
>     * the library that federates the massa wallets creates an invisible HTML element in the DOM and attaches a listener to it
> 
>     * the wallets that want to register as "wallet managers on massa" trigger an event on this element
> 
>     * the library then contacts the chosen wallet manager to ask it to sign a given transaction.
> 
>     * the wallet manager returns the signed transaction also using an event.
> 
> Using events will make communication with the browser extension easier and more secure.
> 
> Finally, standardizing this point means to:
> 
>     * specifying the id of the invisible HTMl element injected into the DOM
> 
>     * specify the format of the wallet_manager.Register event
> 
>     * specify the format of the wallet_manager.Sign event
> 
>     * specify the format of the wallet_manager.SignatureResponse event
> 
> 
> Thyra being the exception for now.

I agree. @massalabs/run @massalabs/innovation can you synchronize to define that standard (it's high priority because community dapps are coming) ?

**Comment by BatiGencho** [comment]
[https://github.com/massalabs/massa-standards/issues/13](url) adding just for reference

**Comment by BatiGencho** [comment]
I have the following question about Thyra: @Thykof @gregLibert @SlnPons 

Thyra seems to have a backend server and a frontend which enables the deployment and downloading of dapps. Now, when I download a dapp, my question is: thyra would d/n the zip, unzip it and serve the game files (index.html, css etc.) to you or would it directly open the index.html file for you in a separate tab ? 
What I am trying to understand is whether thyra frontend will create something like an iFrame where the dapp will be running (thus having its files served by the thyra server) or would it just open the dapp's index.html file in a new tab after the download ?
The idea of my question is: if Thyra dapps are served by thyra backend and running within thyra frontend, then Thyra Frontend inject objects into the browser window

**Comment by BatiGencho** [comment]
The web3(dapp) - browser plugin/wallet integration was already done by Antoine and me in this project: https://github.com/massalabs/massa-wallet

Here are the interfaces that the wallet plugin exposes for the dapp and also wraps the calls to the web3 client.
https://github.com/massalabs/massa-wallet/blob/main/massa/Wallet.js

Some of them were even added back then to the react template proeject https://github.com/massalabs/create-react-app-massa/commit/48ad41e62583d2aff65760bd94803ef8e7f076aa#diff-e32394065a979fa5f9946665f19f1eb9be87f8387ee12e2f5170b2fc2f594e8e enabling the user to directly use them in the dapp and talk to the wallet.

**Comment by Thykof** [comment]
@BatiGencho thyra frontend don't create a iframe, web-on-chain websites are served like a normal server. maybe we can still inject a peace of code that will do the job. The Job being whatsoever, but the chosen solution is to listen events from created invisible DOM element.

**Comment by gregLibert** [comment]
> Thyra seems to have a backend server and a frontend which enables the deployment and downloading of dapps. Now, when I download a dapp, my question is: thyra would d/n the zip, unzip it and serve the game files (index.html, css etc.) to you or would it directly open the index.html file for you in a separate tab ?
> What I am trying to understand is whether thyra frontend will create something like an iFrame where the dapp will be running (thus having its files served by the thyra server) or would it just open the dapp's index.html file in a new tab after the download ?
> The idea of my question is: if Thyra dapps are served by thyra backend and running within thyra frontend, then Thyra Frontend inject objects into the browser window

Maybe it's time to really use internal products so that we can offer consistent user journeys, tooling and standards.

**Comment by BatiGencho** [comment]
@gregLibert What is your point in light of my comment ?

**Comment by BatiGencho** [comment]
I have the following suggestion regarding our wallet standards:

```
interface IAccountInfo {
  info: IAccount;
  balance: IBalance;
  candidate_datastore_keys: Array<Array<number>>;
  created_blocks: Array<string>;
  created_endorsements: Array<string>;
  created_operations: Array<string>;
  final_datastore_keys: Array<Array<number>>;
  next_block_draws: [ISlot];
  next_endorsement_draws: Array<IEndorsementDraws>;
}

interface IAccount {
  address: string;
  publicKey: string; // base58 encoded public key
  secretKey: string; // base58 encoded private key
  thread?: number;
}

interface IBalance {
  final_coins: MassaAmount;
  final_rolls: MassaAmount;
  candidate_coins: MassaAmount;
  candidate_rolls: MassaAmount;
}

interface ISignature {
  base58Encoded: string;
}

interface IRollsData {
  fee: MassaAmount;
  amount: MassaAmount;
}

interface ITransactionData {
  fee: MassaAmount;
  amount: MassaAmount;
  recipientAddress: string;
}

interface IOperationId {
  opId: string;
}

interface IWalletClient {
  // emptying
  emptyWallet(): void;

  // setters
  addSecretKeysToWallet(secretKeys: [string]): [IAccount];
  removeAccountsFromWallet(addresses: [string]);

  // getters
  getAccounts(addresses: [string]): [IAccount];
  getFullAccounts(addresses: [string]): [IAccountInfo];

  // balances
  getAccountBalances(address: [string]): [IBalance];

  // transactions and signing
  signMessage( data: string | Buffer, accountSignerAddress: string): ISignature;
  sendTransaction(txData: ITransactionData, signerAddress: string): IOperationId;
  buyRolls(txData: IRollsData, signerAddress: string): IOperationId;
  sellRolls(txData: IRollsData, signerAddress: string): IOperationId;

  // static
  static async getAccountFromSecretKey(secretKeyBase58: string): IAccount;
  static async walletSignMessage(data: string | Buffer, signerAddress: string): ISignature
}


```

I think this pseudocode speaks for itself!

**Comment by Thykof** [comment]
why provide the private key in getAccounts and getFullAccounts?

**Comment by BatiGencho** [comment]
@Thykof  good point, I have fixed it.

**Comment by gregLibert** [comment]
> I have the following suggestion regarding our wallet standards:
> 
> ```
...
> ```
> 
> I think this pseudocode speaks for itself!

This is not a standard, but a list of interfaces that go beyond the initial requirement.

Can we please focus on :
- something simple enough to cover the initial need to move forward quickly
- be consistent with what has been exchanged, especially why the comment [here](https://github.com/massalabs/massa-standards/issues/13#issuecomment-1440293645), supported by [here](https://github.com/massalabs/massa-standards/issues/13#issuecomment-1441832573).  If I talk about an [event communication](https://developer.chrome.com/docs/extensions/mv3/messaging/), it is not by accident.

If necessary, @innovation can lead the topic.

**Comment by BatiGencho** [comment]
@gregLibert The event messaging is nothing new to Massa. it was already done here: https://github.com/massalabs/massa-wallet and used here https://github.com/massalabs/massa-react-wallet. Instead of having a plugin as in the link, the calls could be redirected to Thyra. I believe that is a very good first step towards making it work.

**Comment by SlnPons** [comment]
@BatiGencho, @gregLibert, @Thykof why don't we do as suggested by Damir and we coordinate properly with a meeting. This back and forth on comments is not the right way to work on important AND urgent topics. 
Thank you Nathan for organising a meeting, let's discuss this and find a solution that fits everyone needs this afternoon as planed :)

**Comment by BatiGencho** [comment]
I agree @SlnPons  I will try to join today eventhough I have taken it as a day off due to National Day. There are far too many aspects and angles that require discussion rather than writing. To be honest, I dont know what Thyra's wallet requirements are. It looks like it has its own specific desires that we better talk out.
