### ISSUE TITLE
NFT Standard NFT 0 never minted

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/massa-standards#143]
## Describe the bug

In the mint function of the NFT we increment the ID and then we save this ID in the key. So the NFT ID 0 is never used.

## Expected behavior

The NFT ID 0 should be the first one otherwise it could lead to confusion while iterating

## Version
```
"@massalabs/sc-standards": "^0.1.1",
```
## Additional context

*Add any other context about the problem here.*

**Comment by leoloco** [comment]
In the ERC721 standard, there is no assumption on the logic of the mint function, and thus on how should the tokenId be generated/incremented. 
Thus, if our goal is to provide a standard similar to ethereum ERC721 standard, we should implement an internal `_mint` function that expects a tokenId as a parameter and let smart contract developers wrap this method with the logic they want for tokenId generation/incrementation.

**Comment by AurelienFT** [comment]
I don't know about ETH personally it was more like a logical issue for a developer that might except an ID that we don't provide to start to 0 and increment one by one (except my LUA homies)

**Comment by leoloco** [comment]
I understand. But as I explained, this issue is irrelevant, because there shouldn't be an implementation of the `mint` function in the fungible token standard. There could an internal `_mint` function that takes as a parameter `tokenId` and `to` to be wrapped by developers.

**Comment by leoloco** [comment]
https://github.com/massalabs/massa-standards/issues/144
