### ISSUE TITLE
MAS coin unit standard

### ISSUE THREAD

**Issue by Thykof** [massalabs/massa-standards#20]
## Context

*Describe / explain why we should do this: motivations, context or other info.

MAS coin has 9 decimals. This issue is about writing a standard that describe how are handle coin amounts.

## How to

*List the step-by-step to get it do if needed (optional)

**proposal**

10^-9 MAS = 0,000 000 001 MAS = 1 nMAS (nano Massa)

**Comment by Thykof** [comment]
related to https://github.com/massalabs/massa-web3/pull/109

**Comment by BatiGencho** [comment]
[https://github.com/massalabs/massa-standards/pull/28](url) The MR for the units standard

**Comment by SlnPons** [comment]
To consider this issue done, I think the standard created should be listed and shared broadly so everyone in the company knows where it is. 
Maybe adding it into "Notion/Massa All/Procedure/ ?" 
@Thykof what do you think? Feel free to suggest another way of doing (wondering is listing it on the github read me wouldn't be more efficient as it will cover internat & external needs at the same time.... how are other companies doing usually?)

**Comment by Thykof** [comment]
we definitely need to update the list in the readme at least.

**Comment by gregLibert** [comment]
> we definitely need to update the list in the readme at least.

The read me needs to be updated indeed...

**Comment by gregLibert** [comment]
@SlnPons @Thykof this was done in #35

**Comment by Thykof** [comment]
thanks!
