### ISSUE TITLE
refactor websiteDeployer

### ISSUE THREAD

**Issue by SebastienValla** [massalabs/massa-standards#4]
Context
In order to earn time when deploy a website on thyra website deployer can be optimized

**User flow**

**How to**
Right now we have 2 functions : 
InitializeWebsite : init the timestamp, the owner and the number of chunks
AppendBytesToWebsite : send website chunks with chunkID, update timestamp.

We wait for initializeWebsite to be over and call appendBytesToWebsites

We could have only one function createWebsite : 
init owner, chunk numbers and timestamp first If not done
send chunks, chunkID, updateTimeStamp

Like this we do not need to wait for initialization function

**Technical details**
Create only one function doing the same thing, 
if !Storage.has(ownerkey) -> init
else -> appendbytetowebsite

**QA testing**
Needs thyra to be updated as well to be tested properly

**Comment by Ben-Rey** [comment]
@longgamma-massa , does this issue still relevant and does it belong to standard ?

**Comment by longgamma-massa** [comment]
@Ben-Rey Here we propose the refactoring needed for a website-deployer standard that could serve multiple use-cases. The SC is still used only for Massa Station purposes. We don't have more info for this topic yet. 

I suggest closing this issue as not planned. I will move the product idea to Notion.
