### ISSUE TITLE
Update Units file

### ISSUE THREAD

**Issue by longgamma-massa** [massalabs/massa-standards#60]
## Context

This page https://github.com/massalabs/massa-standards/blob/main/units.md is outdated. 
Updates needed:
1. Coin symbol should be changed from "Massa" to "XMA", and consequently lower Massa-coin units (nanoXMA etc). 
2. Change mentions of Thyra to MassaStation

## User flow

*Describe the user flow using user stories so the end result is super clear 

## How to

*List the step-by-step to get it do if needed (optional)

## Technical details

*For Dev: give the technical insights so anyone in the team can tackle the tasks

## QA testing

*For Dev: does this task require some QA tests?
*If yes, explain how to validate it*

**Comment by gregLibert** [comment]
@longgamma-massa Is this renaming of Mas to Xma is still accurate?

**Comment by longgamma-massa** [comment]
@gregLibert I closed the issue
