### ISSUE TITLE
Create a burnFrom method

### ISSUE THREAD

**Issue by leoloco** [massalabs/massa-standards#65]
## Context

For some web3 applications, such as lock-mint burn-redeem scheme-based bridges, it is useful for an authorized party to be able to burn some tokens on behalf of their owner. Thus I suggest that we add this method to the token-burn standard. While this feature is not part of the ERC20 standard, it is implemented as a non standard feature by [OpenZeppelin](https://docs.openzeppelin.com/contracts/3.x/api/token/erc20#ERC20Burnable-burnFrom-address-uint256-)

## User flow

The user should increase the allowance of the authorized party. Then, this party should be able to burn tokens on behalf of the user. Obviously, the total supply and allowances should be updated atomically.

## Technical details
```ts
burnFrom(address account, uint256 amount)
```
Destroys amount tokens from account, deducting from the caller’s allowance.

Requirements:
- the caller must have allowance for accounts's tokens of at least amount.

**Comment by leoloco** [comment]
@gregLibert should we add this to massa-standards or should we let specific applications that need this feature to implement their own version?

**Comment by gregLibert** [comment]
> @gregLibert should we add this to massa-standards or should we let specific applications that need this feature to implement their own version?

Let's add that as optional in the massa std.
