### ISSUE TITLE
Fix DNS SC

### ISSUE THREAD

**Issue by B-Naoufal** [massalabs/massa-standards#68]
## Context

*Describe / explain why we should do this: motivations, context or other info. 

## User flow

*Describe the user flow using user stories so the end result is super clear 

## How to

*List the step-by-step to get it do if needed (optional)

## Technical details

*For Dev: give the technical insights so anyone in the team can tackle the tasks

## QA testing

*For Dev: does this task require some QA tests?
*If yes, explain how to validate it*

**Comment by Ben-Rey** [comment]
@peterjah Do you know if this Issue is outdated ?
