### ISSUE TITLE
Readme: invite community to contribute

### ISSUE THREAD

**Issue by Thykof** [massalabs/massa-standards#7]
## Context

*Describe / explain why we should do this: motivations, context or other info. Keep it brief and simple*

We would like to involve the community to develop our standards.

## User flow

*Describe the user flow using user stories so the end result is super clear*

The readme must present how to contribute to the standards

## How to

*List the step-by-step to get it do if needed*

technical contribution:
- [ ] fork, clone
- [ ] setup, install dependencies, run test
- [ ] open a PR

functional contribution:
- [ ] write an issue

## Technical details

*Give the technical insights so anyone in the team can tackle the tasks*

Modify the Readme file, potentially add contribution.md file

## QA testing

*Does this task require some QA tests?*
*If yes, explain how to validate it*

Ask @longgamma-massa for her CR before merging.

**Comment by longgamma-massa** [comment]
@Thykof add context pls

**Comment by Ben-Rey** [comment]
I close this because I think it's outdated : https://github.com/massalabs/massa-standards/blob/main/CONTRIBUTING.md
